(inputTable as table, columnName as text, replacementTable as table) as table =>
        Table.TransformColumns(
            inputTable, 
            {
                {columnName, 
                    each List.Accumulate(
                        Table.ToRows(replacementTable),
                        _,
                        (state, current) =>
                            if state = current{1} then current{2} else state
                    ), 
                    type text
                }
            }
        )
